language: node_js

services:
  - docker

script:
  - npm install

after_success:
  - pip install --user awscli
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - docker build -t isen .
  - docker tag isen 530658460091.dkr.ecr.eu-west-1.amazonaws.com/isen
  - docker push 530658460091.dkr.ecr.eu-west-1.amazonaws.com/isen
  - aws cloudformation update-stack --stack-name ecs-task --template-body ecs-task.yaml --parameters ImageName=530658460091.dkr.ecr.eu-west-1.amazonaws.com/isen